### ISSUE TITLE
Publish the package

### ISSUE THREAD

**Issue by fsoikin** [paluh/purescript-undefined-is-not-a-problem#4]
Hi. I don't know of any way to send a message, so opening an issue instead.

The Readme says you're just about to publish, and I was wondering if you needed any help with that.

I was thinking about implementing something like this myself, because we sorely need it at CollegeVine, when I quite serendipitously came across this library that already does exactly what I want. So I'm in the process of installing it in our project and migrating some ugly `Maybe`-powered stuff to it. I was also considering taking it as a dependency of https://github.com/collegevine/purescript-elmish. 

And while it's possible to install the library via Spago and link to a specific commit (which is what I have done for now), it would be so much nicer to pull it from the package set. Which brings me back to the question: is there anything I can do to help you with publishing?

**Comment by paluh** [comment]
Hi Fyodor!

I hope that I didn't mess up anything  during the publishing process. Here you go: https://github.com/purescript/package-sets/pull/779

I'm also not sure how this API is going to work on a larger code sample. I'm using it currently on the surface of some of our internal libs and it seems to be ok so far

**Comment by fsoikin** [comment]
Oh nice, thank you very much!

**Comment by paluh** [comment]
@fsoikin I've forgotten to rename core pieces before the release. I think I'm going to follow @jvliwanag [suggestions](https://discourse.purescript.org/t/coercible-for-ffi/1914/5) and rename: `Coerce` to `Castable` and `coerce` to `cast`. I can make this switch + release on weekend. I hope that it is not a big deal at this point for you.

**Comment by paluh** [comment]
What do you think about these new names? :-)

**Comment by fsoikin** [comment]
No, it's not a big deal for me. We only have it in one place so far, so it would be easy to upgrade.

As for the names, I don't really like either `cast` or `coerce`. Neither of them seem to convey the meaning well. But I don't have any other ideas, so I'm fine with whatever it will be.
